completed view all grades | Patrick
patahrak/student-grade-table pull request #1
Opened 2020-05-08 04:30 UTC by patahrak

2020-05-08 04:35 UTC, patahrak commented
![image](https://user-images.githubusercontent.com/58499333/81370670-9d880a80-90aa-11ea-9dbe-64555a648f71.png)

2020-05-08 17:49 UTC, scbowler requested changes
Looking good and you are really close, just need a little cleanup in your `GradeTable` class. See below comment.

2020-05-08 17:49 UTC, scbowler commented on components/grade-table.js
> +      $("tbody").append(row, fullName, course, grade);
Here everything is done in "core" javascript except line #16. You usually don't want to mix core and jQuery you should stick to one or the other. Also you already have a pointer to the `tbody` on line 6 so on line 16 you should't re-query the DOM with jQuery to get another reference to the tbody element. You should change line 16 to use core JavaScript and utilize the `tbody` var you already created above. Look into [appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) or [append](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append)

2020-05-09 17:17 UTC, WhiskeyJack96 approved these changes

2020-05-09 17:17 UTC, WhiskeyJack96 commented on components/apps.js
> +  constructor (gradeTable) {
Usually the constuctor should be the first method in a class. You dont need to change it now, but before the next pr you should change it

2020-05-09 17:23 UTC, merged